import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Next.js",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.ico", // Correct path
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/favicon.ico" />
      </head>
      <body>{children}</body>
    </html>
  );
}
